// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/checkin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED    PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_NOT_APPLICABLE PaymentStatus = 1 // montlhy active, should not request it
	PaymentStatus_PAYMENT_STATUS_PAID           PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_ON_CREDIT      PaymentStatus = 3
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_NOT_APPLICABLE",
		2: "PAYMENT_STATUS_PAID",
		3: "PAYMENT_STATUS_ON_CREDIT",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED":    0,
		"PAYMENT_STATUS_NOT_APPLICABLE": 1,
		"PAYMENT_STATUS_PAID":           2,
		"PAYMENT_STATUS_ON_CREDIT":      3,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_checkin_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_api_proto_checkin_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_checkin_proto_rawDescGZIP(), []int{0}
}

type CheckInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	PaymentStatus PaymentStatus          `protobuf:"varint,2,opt,name=payment_status,json=paymentStatus,proto3,enum=gym.PaymentStatus" json:"payment_status,omitempty"` // server ignores it if member is montlhy and active
	PaymentNote   string                 `protobuf:"bytes,3,opt,name=payment_note,json=paymentNote,proto3" json:"payment_note,omitempty"`                               // optional: amount or detail
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInRequest) Reset() {
	*x = CheckInRequest{}
	mi := &file_api_proto_checkin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInRequest) ProtoMessage() {}

func (x *CheckInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_checkin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInRequest.ProtoReflect.Descriptor instead.
func (*CheckInRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_checkin_proto_rawDescGZIP(), []int{0}
}

func (x *CheckInRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *CheckInRequest) GetPaymentStatus() PaymentStatus {
	if x != nil {
		return x.PaymentStatus
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *CheckInRequest) GetPaymentNote() string {
	if x != nil {
		return x.PaymentNote
	}
	return ""
}

type CheckInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CheckedInAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=checked_in_at,json=checkedInAt,proto3" json:"checked_in_at,omitempty"`
	PaymentStatus PaymentStatus          `protobuf:"varint,3,opt,name=payment_status,json=paymentStatus,proto3,enum=gym.PaymentStatus" json:"payment_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInResponse) Reset() {
	*x = CheckInResponse{}
	mi := &file_api_proto_checkin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInResponse) ProtoMessage() {}

func (x *CheckInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_checkin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInResponse.ProtoReflect.Descriptor instead.
func (*CheckInResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_checkin_proto_rawDescGZIP(), []int{1}
}

func (x *CheckInResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CheckInResponse) GetCheckedInAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedInAt
	}
	return nil
}

func (x *CheckInResponse) GetPaymentStatus() PaymentStatus {
	if x != nil {
		return x.PaymentStatus
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

type MemberHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckIns      []*CheckInResponse     `protobuf:"bytes,1,rep,name=check_ins,json=checkIns,proto3" json:"check_ins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberHistoryResponse) Reset() {
	*x = MemberHistoryResponse{}
	mi := &file_api_proto_checkin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberHistoryResponse) ProtoMessage() {}

func (x *MemberHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_checkin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberHistoryResponse.ProtoReflect.Descriptor instead.
func (*MemberHistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_checkin_proto_rawDescGZIP(), []int{2}
}

func (x *MemberHistoryResponse) GetCheckIns() []*CheckInResponse {
	if x != nil {
		return x.CheckIns
	}
	return nil
}

var File_api_proto_checkin_proto protoreflect.FileDescriptor

const file_api_proto_checkin_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/checkin.proto\x12\x03gym\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8b\x01\n" +
	"\x0eCheckInRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\x129\n" +
	"\x0epayment_status\x18\x02 \x01(\x0e2\x12.gym.PaymentStatusR\rpaymentStatus\x12!\n" +
	"\fpayment_note\x18\x03 \x01(\tR\vpaymentNote\"\x9c\x01\n" +
	"\x0fCheckInResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12>\n" +
	"\rchecked_in_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vcheckedInAt\x129\n" +
	"\x0epayment_status\x18\x03 \x01(\x0e2\x12.gym.PaymentStatusR\rpaymentStatus\"J\n" +
	"\x15MemberHistoryResponse\x121\n" +
	"\tcheck_ins\x18\x01 \x03(\v2\x14.gym.CheckInResponseR\bcheckIns*\x89\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dPAYMENT_STATUS_NOT_APPLICABLE\x10\x01\x12\x17\n" +
	"\x13PAYMENT_STATUS_PAID\x10\x02\x12\x1c\n" +
	"\x18PAYMENT_STATUS_ON_CREDIT\x10\x03B\tZ\a./protob\x06proto3"

var (
	file_api_proto_checkin_proto_rawDescOnce sync.Once
	file_api_proto_checkin_proto_rawDescData []byte
)

func file_api_proto_checkin_proto_rawDescGZIP() []byte {
	file_api_proto_checkin_proto_rawDescOnce.Do(func() {
		file_api_proto_checkin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_checkin_proto_rawDesc), len(file_api_proto_checkin_proto_rawDesc)))
	})
	return file_api_proto_checkin_proto_rawDescData
}

var file_api_proto_checkin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_checkin_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_checkin_proto_goTypes = []any{
	(PaymentStatus)(0),            // 0: gym.PaymentStatus
	(*CheckInRequest)(nil),        // 1: gym.CheckInRequest
	(*CheckInResponse)(nil),       // 2: gym.CheckInResponse
	(*MemberHistoryResponse)(nil), // 3: gym.MemberHistoryResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_api_proto_checkin_proto_depIdxs = []int32{
	0, // 0: gym.CheckInRequest.payment_status:type_name -> gym.PaymentStatus
	4, // 1: gym.CheckInResponse.checked_in_at:type_name -> google.protobuf.Timestamp
	0, // 2: gym.CheckInResponse.payment_status:type_name -> gym.PaymentStatus
	2, // 3: gym.MemberHistoryResponse.check_ins:type_name -> gym.CheckInResponse
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_checkin_proto_init() }
func file_api_proto_checkin_proto_init() {
	if File_api_proto_checkin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_checkin_proto_rawDesc), len(file_api_proto_checkin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_checkin_proto_goTypes,
		DependencyIndexes: file_api_proto_checkin_proto_depIdxs,
		EnumInfos:         file_api_proto_checkin_proto_enumTypes,
		MessageInfos:      file_api_proto_checkin_proto_msgTypes,
	}.Build()
	File_api_proto_checkin_proto = out.File
	file_api_proto_checkin_proto_goTypes = nil
	file_api_proto_checkin_proto_depIdxs = nil
}
