// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/member.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemberType int32

const (
	MemberType_MEMBER_TYPE_UNSPECIFIED MemberType = 0
	MemberType_MEMBER_TYPE_MONTHLY     MemberType = 1
	MemberType_MEMBER_TYPE_OCCASIONAL  MemberType = 2
)

// Enum value maps for MemberType.
var (
	MemberType_name = map[int32]string{
		0: "MEMBER_TYPE_UNSPECIFIED",
		1: "MEMBER_TYPE_MONTHLY",
		2: "MEMBER_TYPE_OCCASIONAL",
	}
	MemberType_value = map[string]int32{
		"MEMBER_TYPE_UNSPECIFIED": 0,
		"MEMBER_TYPE_MONTHLY":     1,
		"MEMBER_TYPE_OCCASIONAL":  2,
	}
)

func (x MemberType) Enum() *MemberType {
	p := new(MemberType)
	*p = x
	return p
}

func (x MemberType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemberType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_member_proto_enumTypes[0].Descriptor()
}

func (MemberType) Type() protoreflect.EnumType {
	return &file_api_proto_member_proto_enumTypes[0]
}

func (x MemberType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemberType.Descriptor instead.
func (MemberType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_member_proto_rawDescGZIP(), []int{0}
}

type MemberRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone           string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Type            MemberType             `protobuf:"varint,3,opt,name=type,proto3,enum=gym.MemberType" json:"type,omitempty"`
	MembershipStart *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=membership_start,json=membershipStart,proto3" json:"membership_start,omitempty"` // only on type = MONTHLY
	MembershipEnd   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=membership_end,json=membershipEnd,proto3" json:"membership_end,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MemberRequest) Reset() {
	*x = MemberRequest{}
	mi := &file_api_proto_member_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberRequest) ProtoMessage() {}

func (x *MemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_member_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberRequest.ProtoReflect.Descriptor instead.
func (*MemberRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_member_proto_rawDescGZIP(), []int{0}
}

func (x *MemberRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MemberRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *MemberRequest) GetType() MemberType {
	if x != nil {
		return x.Type
	}
	return MemberType_MEMBER_TYPE_UNSPECIFIED
}

func (x *MemberRequest) GetMembershipStart() *timestamppb.Timestamp {
	if x != nil {
		return x.MembershipStart
	}
	return nil
}

func (x *MemberRequest) GetMembershipEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.MembershipEnd
	}
	return nil
}

type MemberResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone            string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Type             MemberType             `protobuf:"varint,4,opt,name=type,proto3,enum=gym.MemberType" json:"type,omitempty"`
	MembershipEnd    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=membership_end,json=membershipEnd,proto3" json:"membership_end,omitempty"`
	MembershipActive bool                   `protobuf:"varint,6,opt,name=membership_active,json=membershipActive,proto3" json:"membership_active,omitempty"` // server-side calculated with Member.IsMembershipActive()
	Message          string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MemberResponse) Reset() {
	*x = MemberResponse{}
	mi := &file_api_proto_member_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberResponse) ProtoMessage() {}

func (x *MemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_member_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberResponse.ProtoReflect.Descriptor instead.
func (*MemberResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_member_proto_rawDescGZIP(), []int{1}
}

func (x *MemberResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MemberResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MemberResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *MemberResponse) GetType() MemberType {
	if x != nil {
		return x.Type
	}
	return MemberType_MEMBER_TYPE_UNSPECIFIED
}

func (x *MemberResponse) GetMembershipEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.MembershipEnd
	}
	return nil
}

func (x *MemberResponse) GetMembershipActive() bool {
	if x != nil {
		return x.MembershipActive
	}
	return false
}

func (x *MemberResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_api_proto_member_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_member_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_member_proto_rawDescGZIP(), []int{2}
}

type ListMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*MemberResponse      `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_api_proto_member_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_member_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_member_proto_rawDescGZIP(), []int{3}
}

func (x *ListMembersResponse) GetMembers() []*MemberResponse {
	if x != nil {
		return x.Members
	}
	return nil
}

type UpdateMemberRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone           string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	MembershipStart *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=membership_start,json=membershipStart,proto3" json:"membership_start,omitempty"`
	MembershipEnd   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=membership_end,json=membershipEnd,proto3" json:"membership_end,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateMemberRequest) Reset() {
	*x = UpdateMemberRequest{}
	mi := &file_api_proto_member_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberRequest) ProtoMessage() {}

func (x *UpdateMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_member_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberRequest.ProtoReflect.Descriptor instead.
func (*UpdateMemberRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_member_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateMemberRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMemberRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMemberRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateMemberRequest) GetMembershipStart() *timestamppb.Timestamp {
	if x != nil {
		return x.MembershipStart
	}
	return nil
}

func (x *UpdateMemberRequest) GetMembershipEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.MembershipEnd
	}
	return nil
}

type IdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdRequest) Reset() {
	*x = IdRequest{}
	mi := &file_api_proto_member_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdRequest) ProtoMessage() {}

func (x *IdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_member_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdRequest.ProtoReflect.Descriptor instead.
func (*IdRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_member_proto_rawDescGZIP(), []int{5}
}

func (x *IdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_api_proto_member_proto protoreflect.FileDescriptor

const file_api_proto_member_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/member.proto\x12\x03gym\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17api/proto/checkin.proto\"\xe8\x01\n" +
	"\rMemberRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12#\n" +
	"\x04type\x18\x03 \x01(\x0e2\x0f.gym.MemberTypeR\x04type\x12E\n" +
	"\x10membership_start\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0fmembershipStart\x12A\n" +
	"\x0emembership_end\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rmembershipEnd\"\xf9\x01\n" +
	"\x0eMemberResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12#\n" +
	"\x04type\x18\x04 \x01(\x0e2\x0f.gym.MemberTypeR\x04type\x12A\n" +
	"\x0emembership_end\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rmembershipEnd\x12+\n" +
	"\x11membership_active\x18\x06 \x01(\bR\x10membershipActive\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\"\x14\n" +
	"\x12ListMembersRequest\"D\n" +
	"\x13ListMembersResponse\x12-\n" +
	"\amembers\x18\x01 \x03(\v2\x13.gym.MemberResponseR\amembers\"\xd9\x01\n" +
	"\x13UpdateMemberRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12E\n" +
	"\x10membership_start\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0fmembershipStart\x12A\n" +
	"\x0emembership_end\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rmembershipEnd\"\x1b\n" +
	"\tIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id*^\n" +
	"\n" +
	"MemberType\x12\x1b\n" +
	"\x17MEMBER_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13MEMBER_TYPE_MONTHLY\x10\x01\x12\x1a\n" +
	"\x16MEMBER_TYPE_OCCASIONAL\x10\x022\xbc\x02\n" +
	"\n" +
	"GymService\x127\n" +
	"\fCreateMember\x12\x12.gym.MemberRequest\x1a\x13.gym.MemberResponse\x12@\n" +
	"\vListMembers\x12\x17.gym.ListMembersRequest\x1a\x18.gym.ListMembersResponse\x12=\n" +
	"\fUpdateMember\x12\x18.gym.UpdateMemberRequest\x1a\x13.gym.MemberResponse\x124\n" +
	"\aCheckIn\x12\x13.gym.CheckInRequest\x1a\x14.gym.CheckInResponse\x12>\n" +
	"\x10GetMemberHistory\x12\x0e.gym.IdRequest\x1a\x1a.gym.MemberHistoryResponseB\tZ\a./protob\x06proto3"

var (
	file_api_proto_member_proto_rawDescOnce sync.Once
	file_api_proto_member_proto_rawDescData []byte
)

func file_api_proto_member_proto_rawDescGZIP() []byte {
	file_api_proto_member_proto_rawDescOnce.Do(func() {
		file_api_proto_member_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_member_proto_rawDesc), len(file_api_proto_member_proto_rawDesc)))
	})
	return file_api_proto_member_proto_rawDescData
}

var file_api_proto_member_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_member_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_member_proto_goTypes = []any{
	(MemberType)(0),               // 0: gym.MemberType
	(*MemberRequest)(nil),         // 1: gym.MemberRequest
	(*MemberResponse)(nil),        // 2: gym.MemberResponse
	(*ListMembersRequest)(nil),    // 3: gym.ListMembersRequest
	(*ListMembersResponse)(nil),   // 4: gym.ListMembersResponse
	(*UpdateMemberRequest)(nil),   // 5: gym.UpdateMemberRequest
	(*IdRequest)(nil),             // 6: gym.IdRequest
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*CheckInRequest)(nil),        // 8: gym.CheckInRequest
	(*CheckInResponse)(nil),       // 9: gym.CheckInResponse
	(*MemberHistoryResponse)(nil), // 10: gym.MemberHistoryResponse
}
var file_api_proto_member_proto_depIdxs = []int32{
	0,  // 0: gym.MemberRequest.type:type_name -> gym.MemberType
	7,  // 1: gym.MemberRequest.membership_start:type_name -> google.protobuf.Timestamp
	7,  // 2: gym.MemberRequest.membership_end:type_name -> google.protobuf.Timestamp
	0,  // 3: gym.MemberResponse.type:type_name -> gym.MemberType
	7,  // 4: gym.MemberResponse.membership_end:type_name -> google.protobuf.Timestamp
	2,  // 5: gym.ListMembersResponse.members:type_name -> gym.MemberResponse
	7,  // 6: gym.UpdateMemberRequest.membership_start:type_name -> google.protobuf.Timestamp
	7,  // 7: gym.UpdateMemberRequest.membership_end:type_name -> google.protobuf.Timestamp
	1,  // 8: gym.GymService.CreateMember:input_type -> gym.MemberRequest
	3,  // 9: gym.GymService.ListMembers:input_type -> gym.ListMembersRequest
	5,  // 10: gym.GymService.UpdateMember:input_type -> gym.UpdateMemberRequest
	8,  // 11: gym.GymService.CheckIn:input_type -> gym.CheckInRequest
	6,  // 12: gym.GymService.GetMemberHistory:input_type -> gym.IdRequest
	2,  // 13: gym.GymService.CreateMember:output_type -> gym.MemberResponse
	4,  // 14: gym.GymService.ListMembers:output_type -> gym.ListMembersResponse
	2,  // 15: gym.GymService.UpdateMember:output_type -> gym.MemberResponse
	9,  // 16: gym.GymService.CheckIn:output_type -> gym.CheckInResponse
	10, // 17: gym.GymService.GetMemberHistory:output_type -> gym.MemberHistoryResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_member_proto_init() }
func file_api_proto_member_proto_init() {
	if File_api_proto_member_proto != nil {
		return
	}
	file_api_proto_checkin_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_member_proto_rawDesc), len(file_api_proto_member_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_member_proto_goTypes,
		DependencyIndexes: file_api_proto_member_proto_depIdxs,
		EnumInfos:         file_api_proto_member_proto_enumTypes,
		MessageInfos:      file_api_proto_member_proto_msgTypes,
	}.Build()
	File_api_proto_member_proto = out.File
	file_api_proto_member_proto_goTypes = nil
	file_api_proto_member_proto_depIdxs = nil
}
