// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/member.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Plan          string                 `protobuf:"bytes,3,opt,name=plan,proto3" json:"plan,omitempty"` // Ex: "Monthly", "VIP"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberRequest) Reset() {
	*x = MemberRequest{}
	mi := &file_api_proto_member_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberRequest) ProtoMessage() {}

func (x *MemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_member_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberRequest.ProtoReflect.Descriptor instead.
func (*MemberRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_member_proto_rawDescGZIP(), []int{0}
}

func (x *MemberRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MemberRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *MemberRequest) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

type MemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "Active", "Expired"
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberResponse) Reset() {
	*x = MemberResponse{}
	mi := &file_api_proto_member_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberResponse) ProtoMessage() {}

func (x *MemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_member_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberResponse.ProtoReflect.Descriptor instead.
func (*MemberResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_member_proto_rawDescGZIP(), []int{1}
}

func (x *MemberResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MemberResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MemberResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MemberResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type IdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdRequest) Reset() {
	*x = IdRequest{}
	mi := &file_api_proto_member_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdRequest) ProtoMessage() {}

func (x *IdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_member_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdRequest.ProtoReflect.Descriptor instead.
func (*IdRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_member_proto_rawDescGZIP(), []int{2}
}

func (x *IdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_api_proto_member_proto protoreflect.FileDescriptor

const file_api_proto_member_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/member.proto\x12\x03gym\"M\n" +
	"\rMemberRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04plan\x18\x03 \x01(\tR\x04plan\"f\n" +
	"\x0eMemberResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\x1b\n" +
	"\tIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2}\n" +
	"\n" +
	"GymService\x127\n" +
	"\fCreateMember\x12\x12.gym.MemberRequest\x1a\x13.gym.MemberResponse\x126\n" +
	"\x0fGetMemberStatus\x12\x0e.gym.IdRequest\x1a\x13.gym.MemberResponseB\tZ\a./protob\x06proto3"

var (
	file_api_proto_member_proto_rawDescOnce sync.Once
	file_api_proto_member_proto_rawDescData []byte
)

func file_api_proto_member_proto_rawDescGZIP() []byte {
	file_api_proto_member_proto_rawDescOnce.Do(func() {
		file_api_proto_member_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_member_proto_rawDesc), len(file_api_proto_member_proto_rawDesc)))
	})
	return file_api_proto_member_proto_rawDescData
}

var file_api_proto_member_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_member_proto_goTypes = []any{
	(*MemberRequest)(nil),  // 0: gym.MemberRequest
	(*MemberResponse)(nil), // 1: gym.MemberResponse
	(*IdRequest)(nil),      // 2: gym.IdRequest
}
var file_api_proto_member_proto_depIdxs = []int32{
	0, // 0: gym.GymService.CreateMember:input_type -> gym.MemberRequest
	2, // 1: gym.GymService.GetMemberStatus:input_type -> gym.IdRequest
	1, // 2: gym.GymService.CreateMember:output_type -> gym.MemberResponse
	1, // 3: gym.GymService.GetMemberStatus:output_type -> gym.MemberResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_member_proto_init() }
func file_api_proto_member_proto_init() {
	if File_api_proto_member_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_member_proto_rawDesc), len(file_api_proto_member_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_member_proto_goTypes,
		DependencyIndexes: file_api_proto_member_proto_depIdxs,
		MessageInfos:      file_api_proto_member_proto_msgTypes,
	}.Build()
	File_api_proto_member_proto = out.File
	file_api_proto_member_proto_goTypes = nil
	file_api_proto_member_proto_depIdxs = nil
}
