// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: api/proto/member.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GymService_CreateMember_FullMethodName     = "/gym.GymService/CreateMember"
	GymService_ListMembers_FullMethodName      = "/gym.GymService/ListMembers"
	GymService_UpdateMember_FullMethodName     = "/gym.GymService/UpdateMember"
	GymService_CheckIn_FullMethodName          = "/gym.GymService/CheckIn"
	GymService_GetMemberHistory_FullMethodName = "/gym.GymService/GetMemberHistory"
)

// GymServiceClient is the client API for GymService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GymServiceClient interface {
	// gym_id comes from autenticated context (JWT), never from request.
	CreateMember(ctx context.Context, in *MemberRequest, opts ...grpc.CallOption) (*MemberResponse, error)
	ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error)
	UpdateMember(ctx context.Context, in *UpdateMemberRequest, opts ...grpc.CallOption) (*MemberResponse, error)
	CheckIn(ctx context.Context, in *CheckInRequest, opts ...grpc.CallOption) (*CheckInResponse, error)
	GetMemberHistory(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*MemberHistoryResponse, error)
}

type gymServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGymServiceClient(cc grpc.ClientConnInterface) GymServiceClient {
	return &gymServiceClient{cc}
}

func (c *gymServiceClient) CreateMember(ctx context.Context, in *MemberRequest, opts ...grpc.CallOption) (*MemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemberResponse)
	err := c.cc.Invoke(ctx, GymService_CreateMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gymServiceClient) ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMembersResponse)
	err := c.cc.Invoke(ctx, GymService_ListMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gymServiceClient) UpdateMember(ctx context.Context, in *UpdateMemberRequest, opts ...grpc.CallOption) (*MemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemberResponse)
	err := c.cc.Invoke(ctx, GymService_UpdateMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gymServiceClient) CheckIn(ctx context.Context, in *CheckInRequest, opts ...grpc.CallOption) (*CheckInResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckInResponse)
	err := c.cc.Invoke(ctx, GymService_CheckIn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gymServiceClient) GetMemberHistory(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*MemberHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemberHistoryResponse)
	err := c.cc.Invoke(ctx, GymService_GetMemberHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GymServiceServer is the server API for GymService service.
// All implementations must embed UnimplementedGymServiceServer
// for forward compatibility.
type GymServiceServer interface {
	// gym_id comes from autenticated context (JWT), never from request.
	CreateMember(context.Context, *MemberRequest) (*MemberResponse, error)
	ListMembers(context.Context, *ListMembersRequest) (*ListMembersResponse, error)
	UpdateMember(context.Context, *UpdateMemberRequest) (*MemberResponse, error)
	CheckIn(context.Context, *CheckInRequest) (*CheckInResponse, error)
	GetMemberHistory(context.Context, *IdRequest) (*MemberHistoryResponse, error)
	mustEmbedUnimplementedGymServiceServer()
}

// UnimplementedGymServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGymServiceServer struct{}

func (UnimplementedGymServiceServer) CreateMember(context.Context, *MemberRequest) (*MemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMember not implemented")
}
func (UnimplementedGymServiceServer) ListMembers(context.Context, *ListMembersRequest) (*ListMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMembers not implemented")
}
func (UnimplementedGymServiceServer) UpdateMember(context.Context, *UpdateMemberRequest) (*MemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMember not implemented")
}
func (UnimplementedGymServiceServer) CheckIn(context.Context, *CheckInRequest) (*CheckInResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckIn not implemented")
}
func (UnimplementedGymServiceServer) GetMemberHistory(context.Context, *IdRequest) (*MemberHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMemberHistory not implemented")
}
func (UnimplementedGymServiceServer) mustEmbedUnimplementedGymServiceServer() {}
func (UnimplementedGymServiceServer) testEmbeddedByValue()                    {}

// UnsafeGymServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GymServiceServer will
// result in compilation errors.
type UnsafeGymServiceServer interface {
	mustEmbedUnimplementedGymServiceServer()
}

func RegisterGymServiceServer(s grpc.ServiceRegistrar, srv GymServiceServer) {
	// If the following call panics, it indicates UnimplementedGymServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GymService_ServiceDesc, srv)
}

func _GymService_CreateMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GymServiceServer).CreateMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GymService_CreateMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GymServiceServer).CreateMember(ctx, req.(*MemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GymService_ListMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GymServiceServer).ListMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GymService_ListMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GymServiceServer).ListMembers(ctx, req.(*ListMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GymService_UpdateMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GymServiceServer).UpdateMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GymService_UpdateMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GymServiceServer).UpdateMember(ctx, req.(*UpdateMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GymService_CheckIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GymServiceServer).CheckIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GymService_CheckIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GymServiceServer).CheckIn(ctx, req.(*CheckInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GymService_GetMemberHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GymServiceServer).GetMemberHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GymService_GetMemberHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GymServiceServer).GetMemberHistory(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GymService_ServiceDesc is the grpc.ServiceDesc for GymService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GymService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gym.GymService",
	HandlerType: (*GymServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMember",
			Handler:    _GymService_CreateMember_Handler,
		},
		{
			MethodName: "ListMembers",
			Handler:    _GymService_ListMembers_Handler,
		},
		{
			MethodName: "UpdateMember",
			Handler:    _GymService_UpdateMember_Handler,
		},
		{
			MethodName: "CheckIn",
			Handler:    _GymService_CheckIn_Handler,
		},
		{
			MethodName: "GetMemberHistory",
			Handler:    _GymService_GetMemberHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/member.proto",
}
